import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/common/Header";
import Footer from "@/common/Footer";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <Suspense fallback={<div>Loading...</div>}>
        {children}
        </Suspense>
        <Footer/>
        </body>
    </html>
  );
}
